version: '3'
services:
  api:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ./src:/app/
    ports:
      - "3001:3001"
    environment:
      RAILS_ENV: development


